name: Publish NPM Packages

on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  CACHE_VERSION: 20

jobs:
  install-deps:
    name: Install Dependencies
    runs-on: ubuntu-latest

    outputs:
      cache-hit: ${{ steps.cache.outputs.cache-hit }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache (node_modules)
        id: cache
        uses: ./.github/custom-actions/cache-node-modules
        with:
          cache-version: ${{ env.CACHE_VERSION }}

  affected-packages:
    name: Get Affected Packages
    runs-on: ubuntu-latest
    needs: install-deps

    outputs:
      affected: ${{ steps.set-affected.outputs.affected }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache (node_modules)
        id: cache
        uses: ./.github/custom-actions/cache-node-modules
        with:
          cache-version: ${{ env.CACHE_VERSION }}

      - name: Install dependencies
        run: pnpm install --prefer-offline

      - name: Get Affected Libraries
        id: set-affected
        run: |
          AFFECTED=$(npx nx show projects --affected --base=origin/main --head=HEAD --type=lib --exclude=ditto-workspace | tr '\n' ' ')
          echo "Found affected libraries: $AFFECTED"
          echo "affected=$AFFECTED" >> $GITHUB_OUTPUT

  build:
    name: Build Affected Packages
    runs-on: ubuntu-latest
    needs: affected-packages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache (node_modules)
        id: cache
        uses: ./.github/custom-actions/cache-node-modules
        with:
          cache-version: ${{ env.CACHE_VERSION }}

      - name: Install dependencies
        run: pnpm install --prefer-offline

      - name: Build Affected Libraries
        run: |
          for package in ${{ needs.affected-packages.outputs.affected }}; do
            echo "Building $package..."
            npx nx run $package:build
          done
